import React from "react";
import Head from "next/head";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";

export default function Layout({ children, router }) {
  return (
    <>
      <Head>
        <title>株式会社クラシコ</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar path="router.asPath" />
      <main>{children}</main>
      <Footer />
    </>
  );
}
